In [1]:
import numpy as np
import pandas as pd

In [3]:
# Read the training & test data
data = pd.read_csv('Bank_Personal_Loan_Modelling.csv',index_col=0, header=0)


In [4]:
data

Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
ID                                                                            
1      25           1      49     91107       4    1.6          1         0   
2      45          19      34     90089       3    1.5          1         0   
3      39          15      11     94720       1    1.0          1         0   
4      35           9     100     94112       1    2.7          2         0   
5      35           8      45     91330       4    1.0          2         0   
...   ...         ...     ...       ...     ...    ...        ...       ...   
4996   29           3      40     92697       1    1.9          3         0   
4997   30           4      15     92037       4    0.4          1        85   
4998   63          39      24     93023       2    0.3          3         0   
4999   65          40      49     90034       3    0.5          2         0   
5000   28           4      83     92612       3    0.8          1         0   

      Personal Loan  Securities Account  CD Account  Online  CreditCard  
ID                                                                       
1                 0                   1           0       0           0  
2                 0                   1           0       0           0  
3                 0                   0           0       0           0  
4                 0                   0           0       0           0  
5                 0                   0           0       0           1  
...             ...                 ...         ...     ...         ...  
4996              0                   0           0       1           0  
4997              0                   0           0       1           0  
4998              0                   0           0       0           0  
4999              0                   0           0       1           0  
5000              0                   0           0       1           1  

[5000 rows x 13 columns]

In [5]:
# Checking for null values
data.isnull().sum()

Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [7]:
# Check for special characters 

for i in data.columns:
    print(f"Unique value for coulmn: {i}\n\n{data[i].unique()}\n") 

Unique value for coulmn: Age

[25 45 39 35 37 53 50 34 65 29 48 59 67 60 38 42 46 55 56 57 44 36 43 40
 30 31 51 32 61 41 28 49 47 62 58 54 33 27 66 24 52 26 64 63 23]

Unique value for coulmn: Experience

[ 1 19 15  9  8 13 27 24 10 39  5 23 32 41 30 14 18 21 28 31 11 16 20 35
  6 25  7 12 26 37 17  2 36 29  3 22 -1 34  0 38 40 33  4 -2 42 -3 43]

Unique value for coulmn: Income

[ 49  34  11 100  45  29  72  22  81 180 105 114  40 112 130 193  21  25
  63  62  43 152  83 158  48 119  35  41  18  50 121  71 141  80  84  60
 132 104  52 194   8 131 190  44 139  93 188  39 125  32  20 115  69  85
 135  12 133  19  82 109  42  78  51 113 118  64 161  94  15  74  30  38
   9  92  61  73  70 149  98 128  31  58  54 124 163  24  79 134  23  13
 138 171 168  65  10 148 159 169 144 165  59  68  91 172  55 155  53  89
  28  75 170 120  99 111  33 129 122 150 195 110 101 191 140 153 173 174
  90 179 145 200 183 182  88 160 205 164  14 175 103 108 185 204 154 102
 192 202 162 142  95 184 181 143

In [11]:
x= data.values[:,0:8]
y= data.values[:,7]

In [12]:
x

array([[25. ,  1. , 49. , ...,  1.6,  1. ,  0. ],
       [45. , 19. , 34. , ...,  1.5,  1. ,  0. ],
       [39. , 15. , 11. , ...,  1. ,  1. ,  0. ],
       ...,
       [63. , 39. , 24. , ...,  0.3,  3. ,  0. ],
       [65. , 40. , 49. , ...,  0.5,  2. ,  0. ],
       [28. ,  4. , 83. , ...,  0.8,  1. ,  0. ]])

In [13]:
y

array([0., 0., 0., ..., 0., 0., 0.])

In [22]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(x)
x= scaler.transform(x)

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size = 0.3)

In [24]:
X_train.shape

(3500, 8)

In [25]:
Y_train.shape

(3500,)

In [26]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN = KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),metric='euclidean')

In [28]:
model_KNN.fit(X_train,Y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=59)

In [29]:
Y_pred = model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0.0, 0.0), (134.0, 0.0), (0.0, 0.0), (0.0, 0.0), (159.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (112.0, 0.0), (0.0, 0.0), (184.0, 109.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (102.0, 0.0), (135.0, 0.0), (0.0, 0.0), (0.0, 0.0), (171.0, 0.0), (133.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (163.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (177.0, 0.0), (0.0, 0.0), (82.0, 0.0), (0.0, 0.0), (0.0, 0.0), (165.0, 78.0), (104.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (118.0, 0.0), (0.0, 0.0), (0.0, 0.0), (120.0, 0.0), (0.0, 0.0), (80.0, 0.0), (101.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (342.0, 159.0), (0.0, 0.0), (194.0, 0.0), (100.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (587.0, 294.0), (0.0, 0.0), (219.0, 169.0), (0.0, 0.0), (110.0, 0.0), (0.0, 0.0), (170.0, 0.0), (0.0, 0.0), (218.0, 90.0), (0.0,

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm = confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")
print(classification_report(Y_test,Y_pred))

acc = accuracy_score(Y_test,Y_pred)
print("Accuracy of the model:",acc)

[[1011    0    0 ...    0    0    0]
 [   2    0    0 ...    0    0    0]
 [   3    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]
Classification report:
              precision    recall  f1-score   support

         0.0       0.76      1.00      0.86      1011
        75.0       0.00      0.00      0.00         2
        76.0       0.00      0.00      0.00         3
        77.0       0.00      0.00      0.00         1
        78.0       0.00      0.00      0.00         5
        79.0       0.00      0.00      0.00         4
        80.0       0.00      0.00      0.00         3
        81.0       0.00      0.00      0.00         2
        82.0       0.00      0.00      0.00         5
        83.0       0.00      0.00      0.00         5
        84.0       0.00      0.00      0.00         2
        85.0       0.00      0.00      0.00         3
        86.0       0.00      0.00      0.00   

c:\Users\ninad\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ninad\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ninad\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ninad\anaconda3\Lib\site-packages\sklearn\metrics\_cla

In [ ]:
# Accuracy score with KNN was 67.4%

In [21]:
# Let us try with Logistic Regression

In [31]:
from sklearn.linear_model import LogisticRegression

# Create a model object
classifier = LogisticRegression()

# Train the model object
classifier.fit(X_train,Y_train)

LogisticRegression()

In [32]:
Y_pred = classifier.predict(X_test)
print(Y_pred)
print(list(zip(Y_test,Y_pred))) # Here we are using List with zip to show us the list of predictions that are 
                                # classified correctly (e.g. (1,1), (0,0)) 
                                # & those are wrongly classified (e.g. (1,0),(0,1))

[  0. 109.   0. ... 135. 170.   0.]
[(0.0, 0.0), (134.0, 109.0), (0.0, 0.0), (0.0, 0.0), (159.0, 94.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (112.0, 94.0), (0.0, 0.0), (184.0, 130.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (102.0, 81.0), (135.0, 89.0), (0.0, 0.0), (0.0, 0.0), (171.0, 132.0), (133.0, 158.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (163.0, 130.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (177.0, 109.0), (0.0, 0.0), (82.0, 0.0), (0.0, 0.0), (0.0, 0.0), (165.0, 109.0), (104.0, 147.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (118.0, 104.0), (0.0, 0.0), (0.0, 0.0), (120.0, 113.0), (0.0, 0.0), (80.0, 94.0), (101.0, 89.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (342.0, 271.0), (0.0, 0.0), (194.0, 297.0), (100.0, 87.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (587.0, 522.0), (0.0, 0.0), (219.0, 169.0), (0.0, 0.0), (110.0, 87

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm = confusion_matrix(Y_test, Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("accuracy of the model:",acc)

[[1010    0    0 ...    0    0    0]
 [   2    0    0 ...    0    0    0]
 [   2    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.96      1.00      0.98      1011
        75.0       0.00      0.00      0.00         2
        76.0       0.00      0.00      0.00         3
        77.0       0.00      0.00      0.00         1
        78.0       0.00      0.00      0.00         5
        79.0       0.00      0.00      0.00         4
        80.0       0.00      0.00      0.00         3
        81.0       0.00      0.00      0.00         2
        82.0       0.00      0.00      0.00         5
        83.0       0.00      0.00      0.00         5
        84.0       0.00      0.00      0.00         2
        85.0       0.00      0.00      0.00         3
        86.0       0.00      0.00      0.00  

c:\Users\ninad\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ninad\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ninad\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ninad\anaconda3\Lib\site-packages\sklearn\metrics\_cla

In [34]:
# Logistic Regression accuracy : 67.86%

In [ ]:
"""In LogisticRegression I got a slightly better acurracy.
However one needs to perform tuning to make it
better."""